#!/bin/bash

set -e

CCACHE_PREFIX=

EXAMPLE=$1
if [ "$EXAMPLE" == "" ]; then
    exit
fi

NS_DIR=~/workspace/ns-allinone-3.40/ns-3.40

rm -f results/pcap-inet.log results/pcap-ns3.log results/pcap-diff.log
cp $EXAMPLE.cc $NS_DIR/scratch
$NS_DIR/ns3 build scratch/$EXAMPLE
( cd results; $NS_DIR/build/scratch/ns3.40-$EXAMPLE-default )
inet_dbg -u Cmdenv -f $EXAMPLE.ini
tshark -V -r results/General-$EXAMPLE.source.ppp\[0\].pcap > results/pcap-inet.log
tshark -V -r results/$EXAMPLE-0-0.pcap > results/pcap-ns3.log
diff -F '^Frame ' -u results/pcap-ns3.log results/pcap-inet.log > results/pcap-diff.log

